# Generated by Django 5.2.8 on 2025-11-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='Display text for the choice', max_length=255)),
                ('value', models.CharField(help_text='Stored value', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Question Choices',
                'db_table': 'question_choices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionColumn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_columns',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_rows',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variable_name', models.CharField(help_text='Variable identifier for data collection', max_length=100)),
                ('title', models.TextField(help_text='Question text/prompt')),
                ('description', models.TextField(blank=True, help_text='Additional context/help text', null=True)),
                ('is_required', models.BooleanField(default=False, help_text='Must be answered')),
                ('is_initial_question', models.BooleanField(default=False, help_text='First question in flow')),
                ('display_index', models.IntegerField(default=0, help_text='Order of display')),
                ('question_type', models.CharField(help_text='Type of question', max_length=50)),
                ('widget', models.CharField(help_text='UI widget to render', max_length=50)),
                ('file_upload_allowed_extention', models.TextField(blank=True, help_text='For file upload questions (comma-separated)', null=True)),
                ('option_rotation', models.CharField(blank=True, help_text='Randomize option order', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Projects.project')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['display_index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoicesGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('title_align', models.CharField(default='left', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_align', models.CharField(default='left', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('options', models.ManyToManyField(blank=True, related_name='groups', to='Survey.questionchoices')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_groups', to='Survey.question')),
            ],
            options={
                'db_table': 'question_choices_groups',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('title_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='Projects.project')),
                ('questions', models.ManyToManyField(blank=True, related_name='groups', to='Survey.question')),
            ],
            options={
                'db_table': 'question_groups',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['project', 'display_index'], name='questions_project_368405_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_initial_question'], name='questions_is_init_ddf877_idx'),
        ),
    ]
