# Generated by Django 5.2.8 on 2025-11-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projectfilter_variable_and_more'),
        ('Questionlogic', '0001_initial'),
        ('Survey', '0001_initial'),
        ('Users', '0002_user_profile_type_user_signup_type_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input', models.JSONField(blank=True, null=True)),
                ('input_row', models.JSONField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('is_last', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ManyToManyField(blank=True, related_name='answers', to='Survey.questionchoices')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Users.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Projects.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Survey.question')),
                ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='Questionlogic.variable')),
            ],
            options={
                'db_table': 'answers',
                'indexes': [models.Index(fields=['profile', 'project'], name='answers_profile_867fc5_idx'), models.Index(fields=['question'], name='answers_questio_3d2018_idx')],
            },
        ),
    ]
