# Generated by Django 5.2.8 on 2025-11-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('RDO', 'Single Selection (Radio)'), ('CHB', 'Multiple Selection (Checkbox)'), ('DRP', 'Dropdown Menu'), ('TXT', 'Short Text Input'), ('TXTL', 'Long Text Input'), ('RAT', 'Rating Scale (Likert/Star)'), ('NPS', 'Net Promoter Score'), ('SLI', 'Slider Scale'), ('RNK', 'Ranking'), ('MTX', 'Matrix/Grid'), ('FIL', 'File Upload'), ('DT', 'Date/Time Picker'), ('IMG', 'Image Choice'), ('SIG', 'Signature Capture'), ('GEO', 'Geolocation'), ('AV', 'Audio/Video Response')], help_text='Type of question', max_length=5),
        ),
    ]
