# Generated by Django 5.2.8 on 2025-12-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0007_globalfilter_projectquota_project_is_quota_full_and_more"),
        ("Survey", "0003_alter_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_profiling_question",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a standalone profiling question (asked during onboarding)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this question belongs to (null for profiling questions)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="Projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_profiling_question", "display_index"],
                name="questions_is_prof_4306a3_idx",
            ),
        ),
    ]
