# Generated by Django 5.2.8 on 2025-12-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0007_globalfilter_projectquota_project_is_quota_full_and_more"),
        ("Survey", "0004_question_is_profiling_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this answer belongs to (null for profiling answers)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="Projects.project",
            ),
        ),
    ]
