# Generated by Django 5.2.8 on 2025-12-11 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profiling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("state_region", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("primary_language", models.CharField(blank=True, max_length=100)),
                ("mobile_number", models.CharField(blank=True, max_length=20)),
                ("is_mobile_verified", models.BooleanField(default=False)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("is_whatsapp_verified", models.BooleanField(default=False)),
                ("education_level", models.CharField(blank=True, max_length=100)),
                ("participated_in_online_surveys", models.BooleanField(default=False)),
                ("preferred_rewards", models.JSONField(blank=True, default=list)),
                ("consent_invitations", models.BooleanField(default=False)),
                ("consent_data_usage", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiling",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobileOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=10)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("mobile_verify", "Mobile Verification"),
                            ("whatsapp_verify", "WhatsApp Verification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone_number", "purpose", "code"],
                        name="Profiles_mo_phone_n_1e7d11_idx",
                    )
                ],
            },
        ),
    ]
