# Generated by Django 5.2.7 on 2025-10-16 10:11

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('SU', 'Superuser'), ('DV', 'Developer'), ('AD', 'Admin'), ('AM', 'Admin Manager'), ('CM', 'Client Manager'), ('CL', 'Client'), ('AU', 'Audience')], default='AU', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_type',
            field=models.CharField(choices=[('SO', 'Social'), ('SF', 'Self')], default='SF', max_length=2),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('citizen', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('social_id', models.CharField(blank=True, max_length=255)),
                ('mobile_notification_id', models.CharField(blank=True, max_length=255)),
                ('web_notification_id', models.CharField(blank=True, max_length=255)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_terms_accepted', models.BooleanField(default=False)),
                ('is_pp_accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_type', models.CharField(choices=[('SU', 'Superuser'), ('DV', 'Developer'), ('AD', 'Admin'), ('AM', 'Admin Manager'), ('CM', 'Client Manager'), ('CL', 'Client'), ('AU', 'Audience')], max_length=3)),
                ('signup_type', models.CharField(choices=[('SO', 'Social'), ('SF', 'Self')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
