# Generated by Django 5.2.8 on 2026-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_user_profile_type_user_signup_type_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
