"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.utils.timezone import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-6%q%69%6717$2*7v(ow1pn4h8-^g3t08t1^u7_43rt857q&eo3'
SECRET_KEY = "56yex+)g1xo9spba)=)mlr4ux^_@gfog&f3_=3100=zvxx86(f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "portal-staging.quantaigroup.com",
    "localhost",
    "127.0.0.1",
    "portal.quantaigroup.com",
    "quantaitest.loca.lt",
    "quantai-m6zl.onrender.com"
]

CSRF_TRUSTED_ORIGINS = [
    "https://portal-staging.quantaigroup.com",
    "http://localhost:3000",
    "https://portal.quantaigroup.com",
    "https://quantaitest.loca.lt",
    "https://quantai-m6zl.onrender.com"
]

# Application definition

INSTALLED_APPS = [
# default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
# support apps
    "oauth2_provider",
    "rest_framework",
    "social_django",
    "django_filters",
    # "django_q2",
    "phone_field",
    # "geoip2_extras",
    "django_user_agents",
    "drf_spectacular",
# local apps
    "Apps.Users",
    "Apps.Profiles",
    "Apps.Projects",
    "Apps.Transactions",
    "Apps.Wallets",
    "Apps.Rewards",
    "Apps.Survey",
    "Apps.Questionlogic"
]

# Use custom user model defined in Apps.Users
AUTH_USER_MODEL = "Users.User"

# Simple email backend for development — prints emails to console. Replace in production.
# Use real email backend from environment in production; default to console for local dev
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "noreply@quantaigroup.com"

# SMTP Settings (commented out for development, uncomment for production)
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtpout.secureserver.net"
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = "hello@quantaigroup.com"
# EMAIL_HOST_PASSWORD = "QuantAI@365"
# EMAIL_LINK_HOST = "https://portal-staging.quantaigroup.com"

# Load social credentials from environment if set (examples present in your .env)
import os
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_CLIENT_ID")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_SECRET")
SOCIAL_AUTH_FACEBOOK_KEY = os.getenv("SOCIAL_AUTH_FACEBOOK_APP_ID")
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv("SOCIAL_AUTH_FACEBOOK_SECRET")
SOCIAL_AUTH_TWITTER_KEY = os.getenv("SOCIAL_AUTH_TWITTER_API_KEY")
SOCIAL_AUTH_TWITTER_SECRET = os.getenv("SOCIAL_AUTH_TWITTER_SECRET")
SOCIAL_AUTH_APPLE_CLIENT = os.getenv("SOCIAL_AUTH_APPLE_CLIENT_ID")

# Social auth backends
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.apple.AppleIdAuth',
    "oauth2_provider.backends.OAuth2Backend",
    "django.contrib.auth.backends.ModelBackend",
]

# social_django settings
SOCIAL_AUTH_STORAGE = 'social_django.models.DjangoStorage'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login-error/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
# 3rd party
    "django_user_agents.middleware.UserAgentMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # "geoip2_extras.middleware.GeoIP2Middleware",
    "oauth2_provider.middleware.OAuth2TokenMiddleware",
    # "Apps.AuditLog.middleware.AuditlogMiddleware",
    # "libs.middleware.AllowAllCorsMiddleware",  # remove in production
    "django_referrer_policy.middleware.ReferrerPolicyMiddleware",
    "backend.middleware.RequestLoggingMiddleware",
]

REFERRER_POLICY = "strict-origin-when-cross-origin"

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True

DATE_INPUT_FORMATS = [
    "%Y-%m-%d", "%m/%d/%Y", "%d/%m/%Y", "%m/%d/%y",
    "%b %d %Y", "%b %d, %Y", "%d %b %Y", "%d %b, %Y",
    "%B %d %Y", "%B %d, %Y", "%d %B %Y", "%d %B, %Y"
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = "/static/"
if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]
else:
    STATIC_ROOT = BASE_DIR / "static"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# DRF settings
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.authentication.OAuth2Authentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "DATE_FORMAT": "%d %b %Y",
    "DATETIME_FORMAT": "%d-%m-%Y %H:%M",
    "COERCE_DECIMAL_TO_STRING": False,
    # "PAGE_SIZE": 10,
}

LOG_PAGE_SIZE = 30

AUTHENTICATION_BACKENDS = [
    "oauth2_provider.backends.OAuth2Backend",
    "django.contrib.auth.backends.ModelBackend",
]


# Token expiry time
TOKEN_EXPIRE_TIMEDELTA = timedelta(days=360)

# OTP settings (in minutes)
OTP_TTL_MINUTES = 10

# Internal OAuth2 Application for frontend token generation
# This is used when client_id/client_secret are not provided (e.g., Verify OTP, Social Auth)
OAUTH2_INTERNAL_CLIENT_ID = "Rkzsy8StAaD4ChLpxJvYQozOawmMkzG8bRwhD7aU"

INITIAL_LOGIN_REWARDS = 1000
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
            'datefmt': '%d/%b/%Y %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'backend.middleware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

