# Generated by Django 5.2.8 on 2025-11-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0002_alter_project_mode_projectaudiancedetails_and_more'),
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('QV', 'Question Variable'), ('SV', 'Survey Variable'), ('PV', 'Profile Variable'), ('CV', 'Custom Variable')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='Projects.project')),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='Survey.question')),
            ],
            options={
                'db_table': 'variables',
                'indexes': [models.Index(fields=['project', 'name'], name='variables_project_9be7a4_idx'), models.Index(fields=['type'], name='variables_type_e9a963_idx')],
            },
        ),
    ]
