# Generated by Django 5.2.8 on 2025-11-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionlogic', '0001_initial'),
        ('Survey', '0002_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('SKIP_TO', 'Skip To'), ('DISPLAY_IF', 'Display If'), ('END_SURVEY', 'End Survey'), ('MASK_OPTIONS', 'Mask Options')], max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_nodes', to='Survey.question')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_logic', to='Survey.questiongroup')),
                ('target_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_logic', to='Survey.question')),
            ],
            options={
                'db_table': 'logic_nodes',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('EQ', 'Equals'), ('NEQ', 'Not Equals'), ('GT', 'Greater Than'), ('LT', 'Less Than'), ('GTE', 'Greater Than or Equal'), ('LTE', 'Less Than or Equal'), ('CONTAINS', 'Contains'), ('SELECTED', 'Selected'), ('NOT_SELECTED', 'Not Selected')], max_length=20)),
                ('value', models.TextField(blank=True, help_text='Value for CONSTANT comparison', null=True)),
                ('comparison_type', models.CharField(choices=[('CONSTANT', 'Constant Value'), ('VARIABLE', 'Variable/Question')], default='CONSTANT', max_length=20)),
                ('logic_operator', models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_conditions', to='Survey.question')),
                ('target_question', models.ForeignKey(blank=True, help_text='Question for VARIABLE comparison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_conditions', to='Survey.question')),
                ('logic_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='Questionlogic.logicnode')),
            ],
            options={
                'db_table': 'conditions',
            },
        ),
    ]
