# Generated by Django 5.2.8 on 2025-12-14 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0007_globalfilter_projectquota_project_is_quota_full_and_more"),
        ("Questionlogic", "0002_logicnode_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="Projects.project",
            ),
        ),
    ]
