# """
# Django settings for insp project.

# Generated by 'django-admin startproject' using Django 3.1.5.

# For more information on this file, see
# https://docs.djangoproject.com/en/3.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/3.1/ref/settings/
# """

# from pathlib import Path
# from django.utils.timezone import timedelta
# import environ

# # Initialise environment variables
# env = environ.Env()
# environ.Env.read_env()

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env("DJANGO_SECRET_KEY")

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

# CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS")

# # Application definition

# INSTALLED_APPS = [
#     # default apps
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     # support apps
#     "oauth2_provider",
#     "rest_framework",
#     "django_q",
#     "phone_field",
#     "geoip2_extras",
#     "django_user_agents",
#     # local apps
#     "apps.SystemSettings",
#     "apps.AuditLog",
#     "apps.Profiles",
#     "apps.Wallets",
#     "apps.Projects",
#     "apps.Questions",
#     "apps.QuestionGroups",
#     "apps.Transactions",
#     "apps.Variables",
#     "apps.Answers",
# ]

# MIDDLEWARE = [
#     # internal middle ware before needed
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
#     # 3rd party middleware
#     "django_user_agents.middleware.UserAgentMiddleware",
#     "geoip2_extras.middleware.GeoIP2Middleware",
#     "oauth2_provider.middleware.OAuth2TokenMiddleware",
#     "apps.AuditLog.middleware.AuditlogMiddleware",
#     "libs.middleware.AllowAllCorsMiddleware",  # remove this after debug
#     "django_referrer_policy.middleware.ReferrerPolicyMiddleware",
# ]

# REFERRER_POLICY = "strict-origin-when-cross-origin"

# ROOT_URLCONF = "settings.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [
#             BASE_DIR / "templates",
#         ],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.debug",
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "settings.wsgi.application"


# # Database
# # https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# if DEBUG:
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.sqlite3",
#             "NAME": BASE_DIR / "db/db.sqlite3",
#         },
#         'mongo': {
#             'ENGINE': 'djongo',
#             'NAME': 'quantai',
#         }
#     }
# else:
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql_psycopg2",
#             "NAME": env("PG_DATABASE_NAME"),
#             "USER": env("PG_DATABASE_USER"),
#             "PASSWORD": env("PG_DATABASE_PASSWORD"),
#             "HOST": env("PG_DATABASE_HOST"),
#             "PORT": env("PG_DATABASE_PORT"),
#         },
#         "mongo": {
#             "ENGINE": "djongo",
#             "NAME": "quantai",
#         },
#     }

# DATABASE_ROUTER_MAPPING = {
#     # 'SystemSettings' : 'mongo'
# }

# DATABASE_ROUTERS = ["settings.routers.QuantAiRouter"]

# # Password validation
# # https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     # {
#     #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     # },
#     # {
#     #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     # },
#     # {
#     #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     # },
#     # {
#     #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     # },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/3.1/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "Asia/Kolkata"

# USE_I18N = True

# USE_L10N = True

# USE_TZ = True

# DATE_INPUT_FORMATS = [
#     "%Y-%m-%d",  # '2006-10-25'
#     "%m/%d/%Y",  # '10/25/2006'
#     "%d/%m/%Y",  # '25/10/2006'
#     "%m/%d/%y",  # '10/25/06'
#     "%b %d %Y",  # 'Oct 25 2006'
#     "%b %d, %Y",  # 'Oct 25, 2006'
#     "%d %b %Y",  # '25 Oct 2006'
#     "%d %b, %Y",  # '25 Oct, 2006'
#     "%B %d %Y",  # 'October 25 2006'
#     "%B %d, %Y",  # 'October 25, 2006'
#     "%d %B %Y",  # '25 October 2006'
#     "%d %B, %Y",  # '25 October, 2006'
# ]

# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/3.1/howto/static-files/
# STATIC_URL = "/static/"
# if DEBUG:
#     STATIC_ROOT = BASE_DIR / "static"
# else:
#     STATICFILES_DIRS = [
#         BASE_DIR / "static",
#     ]

# MEDIA_ROOT = BASE_DIR / "media"
# MEDIA_URL = "/media/"

# # DRF settings #
# REST_FRAMEWORK = {
#     "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
#     "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "oauth2_provider.contrib.rest_framework.authentication.OAuth2Authentication",
#     ),
#     # Use application/json instead of multipart/form-data requests in tests.
#     "TEST_REQUEST_DEFAULT_FORMAT": "json",
#     "DATE_FORMAT": "%d %b %Y",
#     "DATETIME_FORMAT": "%d-%m-%Y %H:%M",
#     "COERCE_DECIMAL_TO_STRING": False,
#     "PAGE_SIZE": 10,
# }

# LOG_PAGE_SIZE = 30

# AUTHENTICATION_BACKENDS = [
#     "oauth2_provider.backends.OAuth2Backend",
#     "django.contrib.auth.backends.ModelBackend",
# ]

# # Djanog Q settings
# Q_CLUSTER = {
#     "name": "QUANTAI",
#     "workers": 2,
#     "recycle": 500,
#     "timeout": 6000,
#     "retry": 6010,
#     "compress": True,
#     "save_limit": 25000,
#     "queue_limit": 5000,
#     "cpu_affinity": 1,
#     "ack_failures": True,
#     "max_attempts": 0,
#     "attempt_count": 1,
#     "label": "Django Q",
#     "orm": "default",
#     "redis": {
#         "host": "localhost",
#         "port": 6379,
#         "db": 0,
#         "password": None,
#         "socket_timeout": None,
#         "charset": "utf-8",
#         "errors": "strict",
#         "unix_socket_path": None,
#     },
# }

# # Messaging
# ONE_SIGNAL_APP_ID = env("ONE_SIGNAL_APP_ID")


# # Social Keys
# # Apple
# SOCIAL_AUTH_APPLE_KEY_ID = env("SOCIAL_AUTH_APPLE_KEY_ID")
# SOCIAL_AUTH_APPLE_TEAM_ID = env("SOCIAL_AUTH_APPLE_TEAM_ID")
# SOCIAL_AUTH_APPLE_PRIVATE_KEY = env("SOCIAL_AUTH_APPLE_PRIVATE_KEY")
# SOCIAL_AUTH_APPLE_CLIENT_ID = env("SOCIAL_AUTH_APPLE_CLIENT_ID")
# # google
# SOCIAL_AUTH_GOOGLE_CLIENT_ID = env("SOCIAL_AUTH_GOOGLE_CLIENT_ID")
# SOCIAL_AUTH_GOOGLE_CLIENT_SECRET = env("SOCIAL_AUTH_GOOGLE_SECRET")
# # facebook
# SOCIAL_AUTH_FACEBOOK_APP_ID = env("SOCIAL_AUTH_FACEBOOK_APP_ID")
# SOCIAL_AUTH_FACEBOOK_SECRET = env("SOCIAL_AUTH_FACEBOOK_SECRET")
# # twitter
# SOCIAL_AUTH_TWITTER_API_KEY = env("SOCIAL_AUTH_TWITTER_API_KEY")
# SOCIAL_AUTH_TWITTER_SECRET = env("SOCIAL_AUTH_TWITTER_SECRET")

# # Email Settings
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = env("EMAIL_HOST")
# EMAIL_USE_TLS = env("EMAIL_USE_TLS")
# EMAIL_PORT = env("EMAIL_PORT")
# EMAIL_HOST_USER = env("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
# CLIENT_DOMAIN = "https://"
# EMAIL_LINK_HOST = env("EMAIL_LINK_HOST")

# # GeoIP Settings
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
#     },
#     "geoip2-extras": {
#         "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
#     },
# }

# GEOIP_PATH = BASE_DIR / "geoip"
# GEOIP2_EXTRAS_CACHE_NAME = "geoip2-extras"

# # Token expiry time
# TOKEN_EXPIRE_TIMEDELTA = timedelta(days=360)

# INITIAL_LOGIN_REWARDS = 1000

# SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"



"""
Django settings for insp project.
Modified: env variables replaced with actual values.
"""

from pathlib import Path
from django.utils.timezone import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "56yex+)g1xo9spba)=)mlr4ux^_@gfog&f3_=3100=zvxx86(f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "portal-staging.quantaigroup.com",
    "localhost",
    "127.0.0.1",
    "portal.quantaigroup.com",
    "quantaitest.loca.lt",
]

CSRF_TRUSTED_ORIGINS = [
    "https://portal-staging.quantaigroup.com",
    "http://localhost:3000",
    "https://portal.quantaigroup.com",
    "https://quantaitest.loca.lt",
]

# Application definition
INSTALLED_APPS = [
    # default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # support apps
    "oauth2_provider",
    "rest_framework",
    "django_q",
    "phone_field",
    "geoip2_extras",
    "django_user_agents",
    # local apps
    "apps.SystemSettings",
    "apps.AuditLog",
    "apps.Profiles",
    "apps.Wallets",
    "apps.Projects",
    "apps.Questions",
    "apps.QuestionGroups",
    "apps.Transactions",
    "apps.Variables",
    "apps.Answers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 3rd party
    "django_user_agents.middleware.UserAgentMiddleware",
    "geoip2_extras.middleware.GeoIP2Middleware",
    "oauth2_provider.middleware.OAuth2TokenMiddleware",
    "apps.AuditLog.middleware.AuditlogMiddleware",
    "libs.middleware.AllowAllCorsMiddleware",  # remove in production
    "django_referrer_policy.middleware.ReferrerPolicyMiddleware",
]

REFERRER_POLICY = "strict-origin-when-cross-origin"

ROOT_URLCONF = "settings.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "settings.wsgi.application"

# Database
if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db/db.sqlite3",
        },
        "mongo": {
            "ENGINE": "djongo",
            "NAME": "quantai",
        },
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": "quant",
            "USER": "quant",
            "PASSWORD": "quant@123",
            "HOST": "localhost",
            "PORT": "5432",
        },
        "mongo": {
            "ENGINE": "djongo",
            "NAME": "quantai",
        },
    }

DATABASE_ROUTERS = ["settings.routers.QuantAiRouter"]

# Password validation (optional configs commented)

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_L10N = True
USE_TZ = True

DATE_INPUT_FORMATS = [
    "%Y-%m-%d", "%m/%d/%Y", "%d/%m/%Y", "%m/%d/%y",
    "%b %d %Y", "%b %d, %Y", "%d %b %Y", "%d %b, %Y",
    "%B %d %Y", "%B %d, %Y", "%d %B %Y", "%d %B, %Y"
]

STATIC_URL = "/static/"
if DEBUG:
    STATIC_ROOT = BASE_DIR / "static"
else:
    STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# DRF settings
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.authentication.OAuth2Authentication",
    ),
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "DATE_FORMAT": "%d %b %Y",
    "DATETIME_FORMAT": "%d-%m-%Y %H:%M",
    "COERCE_DECIMAL_TO_STRING": False,
    # "PAGE_SIZE": 10,
}

LOG_PAGE_SIZE = 30

AUTHENTICATION_BACKENDS = [
    "oauth2_provider.backends.OAuth2Backend",
    "django.contrib.auth.backends.ModelBackend",
]

# Django Q
Q_CLUSTER = {
    "name": "QUANTAI",
    "workers": 2,
    "recycle": 500,
    "timeout": 6000,
    "retry": 6010,
    "compress": True,
    "save_limit": 25000,
    "queue_limit": 5000,
    "cpu_affinity": 1,
    "ack_failures": True,
    "max_attempts": 0,
    "attempt_count": 1,
    "label": "Django Q",
    "orm": "default",
    "redis": {
        "host": "localhost",
        "port": 6379,
        "db": 0,
        "password": None,
        "socket_timeout": None,
        "charset": "utf-8",
        "errors": "strict",
        "unix_socket_path": None,
    },
}

# Messaging
ONE_SIGNAL_APP_ID = "13d89823-ce55-41b3-a487-421ab60bf1af"

# Social Keys
SOCIAL_AUTH_APPLE_KEY_ID = "a"
SOCIAL_AUTH_APPLE_TEAM_ID = "a"
SOCIAL_AUTH_APPLE_PRIVATE_KEY = "a"
SOCIAL_AUTH_APPLE_CLIENT_ID = "a"

SOCIAL_AUTH_GOOGLE_CLIENT_ID = "335164722698-0j7igimn4qhun50sp6qop24qdgd48n3i.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_CLIENT_SECRET = "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"

SOCIAL_AUTH_FACEBOOK_APP_ID = "1076818853154819"
SOCIAL_AUTH_FACEBOOK_SECRET = "44c24e65123c390bfe59238ba924cca3"

SOCIAL_AUTH_TWITTER_API_KEY = "IRR7UJMo9cvuFUjXZal7QVn3b"
SOCIAL_AUTH_TWITTER_SECRET = "PHyFUDXK9so8guHOYjW54XNN74RKCZpasee61QVB8xJUrqMV6m"

# Email Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtpout.secureserver.net"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "hello@quantaigroup.com"
EMAIL_HOST_PASSWORD = "QuantAI@365"
CLIENT_DOMAIN = "https://"
EMAIL_LINK_HOST = "https://portal-staging.quantaigroup.com"

# GeoIP Settings
CACHES = {
    "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
    "geoip2-extras": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
}

GEOIP_PATH = BASE_DIR / "geoip"
GEOIP2_EXTRAS_CACHE_NAME = "geoip2-extras"

# Token expiry time
TOKEN_EXPIRE_TIMEDELTA = timedelta(days=360)

INITIAL_LOGIN_REWARDS = 1000
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
