# Generated by Django 5.2.8 on 2025-11-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
        ('Survey', '0001_initial'),
        ('Users', '0002_user_profile_type_user_signup_type_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profiling_balance', models.FloatField(default=0.0)),
                ('survey_balance', models.FloatField(default=0.0)),
                ('total_withdrawal', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='Users.profile')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField(default=0.0)),
                ('survey_amount', models.FloatField(default=0.0)),
                ('profiling_amount', models.FloatField(default=0.0)),
                ('t_type', models.CharField(choices=[('DEP', 'Deposit'), ('WID', 'Withdrawal')], max_length=3)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('SU', 'Success'), ('RE', 'Rejected'), ('CA', 'Cancelled')], default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Users.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Projects.project')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Survey.question')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='transaction_profile_8f0ced_idx'), models.Index(fields=['t_type'], name='transaction_t_type_583ded_idx'), models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx')],
            },
        ),
    ]
