# Generated by Django 5.2.8 on 2025-11-08 13:05

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reward_points', models.FloatField(default=0.0, help_text='Points awarded for completion', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('code', models.CharField(help_text='Unique project identifier', max_length=50, unique=True)),
                ('project_type', models.CharField(choices=[('SU', 'Survey'), ('PR', 'Profiling')], max_length=2)),
                ('mode', models.CharField(choices=[('DE', 'Demo'), ('PR', 'Production'), ('DV', 'Development'), ('LI', 'Live'), ('CO', 'Completed')], default='DE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('languages', models.ManyToManyField(blank=True, related_name='projects', to='Projects.language')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='projects_code_7205ea_idx'), models.Index(fields=['project_type'], name='projects_project_3c9de1_idx'), models.Index(fields=['active'], name='projects_active_229ba6_idx'), models.Index(fields=['start_time', 'end_time'], name='projects_start_t_b92729_idx')],
            },
        ),
    ]
