# Generated by Django 5.2.8 on 2025-11-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
        ('Survey', '0001_initial'),
        ('Users', '0002_user_profile_type_user_signup_type_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mode',
            field=models.CharField(choices=[('DE', 'Demo'), ('PR', 'Production'), ('DM', 'Development'), ('LI', 'Live'), ('CO', 'Completed')], default='DE', max_length=2),
        ),
        migrations.CreateModel(
            name='ProjectAudianceDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('last_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_columns', models.ManyToManyField(blank=True, related_name='next_in', to='Survey.questioncolumn')),
                ('next_options', models.ManyToManyField(blank=True, related_name='next_in', to='Survey.questionchoices')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_for', to='Survey.question')),
                ('next_rows', models.ManyToManyField(blank=True, related_name='next_in', to='Survey.questionrow')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='Users.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_details', to='Projects.project')),
            ],
            options={
                'db_table': 'project_audience_details',
            },
        ),
        migrations.CreateModel(
            name='ProjectFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('options', models.ManyToManyField(related_name='filters', to='Survey.questionchoices')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='Projects.project')),
            ],
            options={
                'db_table': 'project_filters',
            },
        ),
    ]
