# Generated by Django 5.2.8 on 2025-11-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_project_mode_projectaudiancedetails_and_more'),
        ('Questionlogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfilter',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='Questionlogic.variable'),
        ),
        migrations.AddIndex(
            model_name='projectaudiancedetails',
            index=models.Index(fields=['project', 'profile'], name='project_aud_project_0b69f8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaudiancedetails',
            index=models.Index(fields=['status'], name='project_aud_status_2be3e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectaudiancedetails',
            unique_together={('project', 'profile')},
        ),
    ]
