# Generated by Django 5.2.8 on 2025-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projectfilter_variable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='answer_preview',
            field=models.BooleanField(default=False, help_text='Allow answer preview before submission'),
        ),
        migrations.AddField(
            model_name='project',
            name='complete_btn_text',
            field=models.CharField(default='Complete', help_text='Complete button text', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='display_thankyou_message',
            field=models.BooleanField(default=False, help_text='Show thank you message'),
        ),
        migrations.AddField(
            model_name='project',
            name='display_welcome_message',
            field=models.BooleanField(default=False, help_text='Show welcome message'),
        ),
        migrations.AddField(
            model_name='project',
            name='fit_logo',
            field=models.BooleanField(default=True, help_text='Fit logo to specified dimensions'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_height',
            field=models.IntegerField(blank=True, help_text='Logo height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_location',
            field=models.CharField(blank=True, choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')], help_text='Logo position on screen', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to project logo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_width',
            field=models.IntegerField(blank=True, help_text='Logo width in pixels', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='navigation_message',
            field=models.TextField(blank=True, help_text='Navigation instructions', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='next_btn_text',
            field=models.CharField(default='Next', help_text='Next button text', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='previous_btn_text',
            field=models.CharField(default='Previous', help_text='Previous button text', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='quotafull_message',
            field=models.TextField(blank=True, help_text='Quota full message text', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show_progress_bar',
            field=models.BooleanField(default=True, help_text='Display progress bar'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_btn_text',
            field=models.CharField(default='Start', help_text='Start button text', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='thankyou_message',
            field=models.TextField(blank=True, help_text='Thank you message text', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='welcome_message',
            field=models.TextField(blank=True, help_text='Welcome message text', null=True),
        ),
    ]
