# Generated by Django 5.2.8 on 2025-12-01 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_project_answer_preview_project_complete_btn_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='participant_limit',
            field=models.IntegerField(blank=True, help_text='Maximum number of participants allowed (e.g., 10000, 50000)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='project',
            name='terminate_message',
            field=models.TextField(blank=True, help_text='Message when survey is closed/terminated', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='quotafull_message',
            field=models.TextField(blank=True, help_text='Message when participant limit is reached', null=True),
        ),
    ]
