# Generated by Django 5.2.8 on 2025-12-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Projects",
            "0005_project_participant_limit_project_terminate_message_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Project logo image file",
                null=True,
                upload_to="projects/logos/",
            ),
        ),
    ]
