# Generated by Django 5.2.7 on 2025-12-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_remove_project_logo_url_project_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logo',
        ),
        migrations.AddField(
            model_name='project',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to project logo', max_length=500, null=True),
        ),
    ]
