# Generated by Django 5.2.8 on 2025-12-13 13:38

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0006_remove_project_logo_url_project_logo"),
        ("Questionlogic", "0002_logicnode_condition"),
        ("Survey", "0003_alter_question_question_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalFilter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this filter", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Explain what this filter does", null=True
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("INCLUDE", "Include Only"), ("EXCLUDE", "Exclude")],
                        default="INCLUDE",
                        max_length=10,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("EQ", "Equals"),
                            ("NEQ", "Not Equals"),
                            ("GT", "Greater Than"),
                            ("LT", "Less Than"),
                            ("GTE", "Greater Than or Equal"),
                            ("LTE", "Less Than or Equal"),
                            ("CONTAINS", "Contains"),
                            ("IN", "In List"),
                            ("NOT_IN", "Not In List"),
                        ],
                        default="EQ",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True, help_text="For constant value comparison", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this filter"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Evaluation order (lower = higher priority)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "global_filters",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="ProjectQuota",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        help_text="Country for this quota", max_length=2
                    ),
                ),
                (
                    "limit",
                    models.IntegerField(
                        help_text="Maximum participants from this country",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "current_count",
                    models.IntegerField(
                        default=0, help_text="Current number of participants"
                    ),
                ),
                (
                    "action_on_full",
                    models.CharField(
                        choices=[
                            ("BLOCK", "Block This Segment"),
                            ("CLOSE", "Close Entire Survey"),
                        ],
                        default="BLOCK",
                        help_text="Action when quota is reached",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FULL", "Quota Full"),
                            ("PAUSED", "Paused"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "project_quotas",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="is_quota_full",
            field=models.BooleanField(
                default=False, help_text="Auto-set when all quotas are full"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quota_full_action",
            field=models.CharField(
                choices=[
                    ("BLOCK", "Block Full Segments Only"),
                    ("CLOSE", "Close Entire Survey"),
                ],
                default="BLOCK",
                help_text="Default action when quotas are full",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projectfilter",
            name="filter_type",
            field=models.CharField(
                choices=[("INCLUDE", "Include Only"), ("EXCLUDE", "Exclude")],
                default="INCLUDE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projectfilter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="projectfilter",
            name="operator",
            field=models.CharField(
                choices=[
                    ("EQ", "Equals"),
                    ("NEQ", "Not Equals"),
                    ("GT", "Greater Than"),
                    ("LT", "Less Than"),
                    ("GTE", "Greater Than or Equal"),
                    ("LTE", "Less Than or Equal"),
                    ("CONTAINS", "Contains"),
                    ("IN", "In List"),
                    ("NOT_IN", "Not In List"),
                ],
                default="EQ",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projectfilter",
            name="value",
            field=models.TextField(
                blank=True,
                help_text="For constant value comparison (age, income, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectfilter",
            name="options",
            field=models.ManyToManyField(
                blank=True,
                help_text="For choice-based filters",
                related_name="filters",
                to="Survey.questionchoices",
            ),
        ),
        migrations.AlterField(
            model_name="projectfilter",
            name="variable",
            field=models.ForeignKey(
                help_text="Variable from profiling question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_filters",
                to="Questionlogic.variable",
            ),
        ),
        migrations.AddIndex(
            model_name="projectfilter",
            index=models.Index(
                fields=["project", "is_active"], name="project_fil_project_7416b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectfilter",
            index=models.Index(
                fields=["filter_type"], name="project_fil_filter__359cb1_idx"
            ),
        ),
        migrations.AddField(
            model_name="globalfilter",
            name="options",
            field=models.ManyToManyField(
                blank=True, related_name="global_filters", to="Survey.questionchoices"
            ),
        ),
        migrations.AddField(
            model_name="globalfilter",
            name="variable",
            field=models.ForeignKey(
                help_text="Variable from profiling question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_filters",
                to="Questionlogic.variable",
            ),
        ),
        migrations.AddField(
            model_name="projectquota",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotas",
                to="Projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="globalfilter",
            index=models.Index(
                fields=["is_active", "priority"], name="global_filt_is_acti_657aa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectquota",
            index=models.Index(
                fields=["project", "status"], name="project_quo_project_63012b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectquota",
            index=models.Index(
                fields=["country"], name="project_quo_country_dbc758_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectquota",
            unique_together={("project", "country")},
        ),
    ]
