# Generated by Django 5.2.7 on 2025-12-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_remove_project_logo_project_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, help_text='Project logo image file', null=True, upload_to='projects/logos/'),
        ),
    ]
