# Generated by Django 5.2.7 on 2025-12-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_add_created_by_to_project'),
        ('Projects', '0008_remove_project_logo_url_project_logo'),
    ]

    operations = [
    ]
